config {
  type: "incremental",
  schema: "mm_preproduction",
  bigquery: {
    partitionBy: "date",
    clusterBy: ["Continent", "ServerSite"]
  }
}

SELECT *,
  server.Geo.ContinentCode AS Continent,
  server.Site AS ServerSite
FROM `measurement-lab.ndt.ndt7_dynamic`
WHERE date >= CURRENT_DATE() - 30
  AND FARM_FINGERPRINT(a.UUID) & 0xF = 0
${ when(incremental(), `AND date > (SELECT MAX(date) FROM ${self()})`) }
