config {
  type: "incremental",
  schema: "mm_preproduction",
  bigquery: {
    partitionBy: "date",
    clusterBy: ["isValidBest", "ServerContinent", "ServerSite"],
    requirePartitionFilter: true
  }
}

WITH

src AS (
  SELECT
    * EXCEPT (Parser),
    [parser.ArchiveURL] AS ArchiveURL,
    'legacy' AS _fleet
  FROM ${ref("ndt7_DS16")}
  WHERE date >= CURRENT_DATE() - 30
  ${ when(incremental(), `AND date > (SELECT MAX(date) FROM ${self()})`) }

  UNION ALL

  SELECT
    * EXCEPT (Archiver),
    [Archiver.ArchiveURL] AS ArchiveURL,
    'autojoin' AS _fleet
  FROM ${ref("autoload_DS16")}
  WHERE date >= CURRENT_DATE() - 30
  ${ when(incremental(), `AND date > (SELECT MAX(date) FROM ${self()})`) }
),

ndt7downloads AS (
  SELECT *,
    raw.Download.ServerMeasurements[SAFE_ORDINAL(ARRAY_LENGTH(raw.Download.ServerMeasurements))]
        AS FinalSnapshot,
    False AS IsError,   -- TODO ndt-server/issues/317
    TIMESTAMP_DIFF(raw.Download.EndTime, raw.Download.StartTime, MILLISECOND) * 1.0 AS test_duration
  FROM src
  WHERE
    raw.Download IS NOT NULL
    AND raw.Download.UUID IS NOT NULL
    AND raw.Download.UUID NOT IN ('', 'ERROR_DISCOVERING_UUID')
),

PreComputeNDT7 AS (
  SELECT
    id, date, ArchiveURL, server, client, a, raw,
    IsError, FinalSnapshot, test_duration,

    FinalSnapshot IS NOT NULL AS IsComplete,

    IF("early_exit" IN (
      SELECT metadata.Name FROM UNNEST(raw.Download.ClientMetadata) AS metadata
    ), True, False) AS IsEarlyExit,

    CONCAT("ndt7",
      IF(raw.ClientIP LIKE "%:%", "-IPv6", "-IPv4"),
      CASE raw.ServerPort
        WHEN 443 THEN "-WSS"
        WHEN 80  THEN "-WS"
        ELSE "-unknown" END
    ) AS Protocol,

    -- TODO(https://github.com/m-lab/etl/issues/893) generalize IsOAM
    (raw.ClientIP IN (
      "35.193.254.117",   -- script-exporter VMs in GCE, sandbox
      "35.225.75.192",    -- script-exporter VM in GCE, staging
      "35.192.37.249",    -- script-exporter VM in GCE, oti
      "23.228.128.99", "2605:a601:f1ff:fffe::99",   -- ks addresses
      "45.56.98.222",  "2600:3c03::f03c:91ff:fe33:819",  -- eb addresses
      "35.202.153.90", "35.188.150.110"  -- Static IPs from GKE VMs for e2e tests
    )) AS IsOAM,

    -- TODO(https://github.com/m-lab/k8s-support/issues/668) deprecate? _IsRFC1918
    (
      (NET.IP_TRUNC(NET.SAFE_IP_FROM_STRING(raw.ClientIP),  8) = NET.IP_FROM_STRING("10.0.0.0"))
      OR (NET.IP_TRUNC(NET.SAFE_IP_FROM_STRING(raw.ClientIP), 12) = NET.IP_FROM_STRING("172.16.0.0"))
      OR (NET.IP_TRUNC(NET.SAFE_IP_FROM_STRING(raw.ClientIP), 16) = NET.IP_FROM_STRING("192.168.0.0"))
    ) AS _IsRFC1918,

    True AS IsProduction,  -- XXX need a better test, or is this redundant?
    _fleet
  FROM ndt7downloads
),

UnifiedDownloadSchema AS (
  SELECT
    id,
    date,
    STRUCT(
      a.UUID,
      a.TestTime,
      'Download' AS Direction,
      a.CongestionControl,
      a.MeanThroughputMbps,
      a.MinRTT,
      a.LossRate
    ) AS a,

    STRUCT(
      'extended_ndt7_downloads' AS View,
      Protocol,
      raw.Download.ClientMetadata AS ClientMetadata,
      raw.Download.ServerMetadata AS ServerMetadata,
      ArchiveURL
    ) AS metadata,

    STRUCT(
      IsComplete,
      IsProduction,
      IsError,
      IsOAM,
      False AS IsPlatformAnomaly,
      (FinalSnapshot.TCPInfo.BytesAcked < 8192) AS IsSmall,
      (test_duration < 9000.0) AS IsShort,
      (test_duration > 60000.0) AS IsLong,
      IsEarlyExit
    ) AS filter,

    STRUCT(
      raw.ClientIP AS IP,
      raw.ClientPort AS Port,
      client.Geo,
      client.Network
    ) AS client,

    STRUCT(
      raw.ServerIP AS IP,
      raw.ServerPort AS Port,
      server.Site,
      server.Machine,
      server.Geo,
      server.Network
    ) AS server,

    _fleet,
    PreComputeNDT7 AS _internal202511
  FROM PreComputeNDT7
),

UnifiedIsValid AS (
  SELECT *,
    (
      filter.IsComplete
      AND filter.IsProduction
      AND NOT filter.IsError
      AND NOT filter.IsOAM
      AND NOT filter.IsPlatformAnomaly
      AND NOT filter.IsSmall
      AND (NOT filter.IsShort OR filter.IsEarlyExit)
      AND NOT filter.IsLong
    ) AS IsValidBest
  FROM UnifiedDownloadSchema
)

SELECT *,
  server.Geo.ContinentCode AS ServerContinent,
  server.Site AS ServerSite
FROM UnifiedIsValid
