config {
  type: "incremental",
  schema: "mm_preproduction",
  name: "ndt7_DS16",
  bigquery: {
    partitionBy: "date",
    clusterBy: ["Continent", "ServerSite"]
  }
}

SELECT
  *,
  server.Geo.ContinentCode AS Continent,
  server.Site AS ServerSite
FROM
  `measurement-lab.ndt.ndt7`
WHERE
  FARM_FINGERPRINT(a.UUID) & 0xF = 0
  -- On the very first run, this ensures we only look for data newer than your current table
  AND date > (SELECT MAX(date) FROM ${self()})
