
config {
  type: "incremental",
  schema: "mm_preproduction",
  name: "scamper1_DS16",
  description: "Subsampled scamper1 data (16:1) with added Continent and ServerSite columns.",
  bigquery: {
    partitionBy: "date",
    clusterBy: ["Continent", "ServerSite"],
  }
}

SELECT
  *,
  -- Add the partitioning/clustering columns
  server.Geo.ContinentCode AS Continent,
  server.Site AS ServerSite
FROM
  `measurement-lab.ndt.scamper1`
WHERE
  -- Don't go too far in the past
  date > '2026-01-01'
  -- Make sure the data from the fleet is stable 
  AND date < CURRENT_DATE() - 1
  -- Incremental logic: only fetch data newer than the existing table
  AND date > (SELECT MAX(date) FROM ${self()} WHERE date > '2026-01-01')
  -- Subsampling 16:1
  AND FARM_FINGERPRINT(raw.Metadata.UUID) & 0xF = 0
